# NOTE: Local macOS Docker Desktop docker compose deployment requires:
#   1. "Docker Desktop" -> "Settings" -> "Resources" -> "Network" -> "Use kernel networking for UDP"
#     enables 'bridge100' network interface allowing UDP communication: 
#     * local server <-> deployed coturn service (when debugging ICE communication)
#     * local client <-> deployed coturn service (when debugging within emulated production infra)
#   2. "Settings" -> "Privacy & Security" -> "Local Network" enable for "Rider"
#     allows local server <-> deployed coturn communication 
#     (otherwise "HostUnreachable", "No route to host" when trying to connect coturn ICE service)

services:
  coturn:
    network_mode: host
