services:
  server:
    build:
      dockerfile: src/App/Server/Dockerfile
    environment:
      # TODO: external setup auto-detection for coturn service 10.211.55.4
      SipRtcConfig__IceServers__0__Urls__0: turn:10.211.55.4:3478
      SipRtcConfig__IceServers__0__Username: user
      SipRtcConfig__IceServers__0__Password: pass
