networks:
  # Manually created shared network (attachable allowing debug from non-swarm containers):
  #   docker network create --driver overlay --attachable general_shared
  # Allows access to different staging stacks from shared general services (nginx, etc)
  general_shared:
    external: true

services:
  server:
    environment:
      # TODO: auto-detect instead of hard-code, coturn bound on host "docker_gwbridge" network interface
      # TODO: coturn setup --relay-ip allowing to access via internal network interface only (turn:172.18.0.1 returns 172.18.0.1 as relay now)
      SipRtcConfig__IceServers__0__Url: turn:${SERVER_NAME:-localhost} 
      SipRtcConfig__IceServers__0__Username: ${TURN_USERNAME:-user}
      SipRtcConfig__IceServers__0__Password: ${TURN_PASSWORD:-pass}
      SipRtcConfig__RemoteConfig__IceServers__0__Url: stun:${SERVER_NAME:-localhost}
    networks:
      general_shared:
        aliases:
          - server.${STAND_NAME:-local}
