name: Remote Deploy Commands
description: Helper to run remote ssh/docker commands
inputs:
  ssh_data:
    required: true
    description: "SSH credentials in format user@host|private_key"
  step_run:
    required: true
    description: commands script
  step_name:
    required: false
    description: step name
    default: Run Deploy Commands

runs:
  using: "composite"
  steps:
    - name: ${{ inputs.step_name }}
      uses: ./.github/composites/remote-ssh
      with:
        ssh_user: ${{ fromJSON(ssh_data).REMOTE_USER }}
        ssh_host: ${{ fromJSON(ssh_data).REMOTE_HOST }}
        ssh_private_key: ${{ fromJSON(ssh_data).REMOTE_PRIVATE_KEY }}
        step_name: ${{ inputs.step_name }}
        step_run: |
          #### ${{ inputs.step_name }}
          # cleanup sensitive variable before run
          sed -i '/^SSH_PKEY=/d' $GITHUB_ENV

          # export variable for implicit docker usage in run
          export DOCKER_HOST="ssh://${SSH_TARGET}"

          ${{ inputs.step_run }}

    - name: Cleanup Deploy Variables
      if: always()
      shell: bash
      run: |
        #### Cleanup exported variables
        sed -i '/^SSH_USER=/d' $GITHUB_ENV
        sed -i '/^SSH_HOST=/d' $GITHUB_ENV
