name: Remote Deploy Commands
description: Helper to run remote ssh/docker commands
inputs:
  step_run:
    required: true
    description: commands script
  step_name:
    required: false
    description: step name
    default: Run Deploy Commands

runs:
  using: "composite"
  steps:
    - name: Setup Deploy Variables
      shell: bash
      run: |
        #### Export useful variables
        # workaround secrets usage in composite action
        echo "SSH_USER=${{ secrets.REMOTE_USER }}" >> $GITHUB_ENV
        echo "SSH_HOST=${{ secrets.REMOTE_HOST }}" >> $GITHUB_ENV
        echo "SSH_PRIVATE_KEY=${{ secrets.REMOTE_PRIVATE_KEY }}" >> $GITHUB_ENV

    - name: Setup SSH and Docker
      uses: ./.github/composites/remote-ssh
      with:
        ssh_user: ${{ env.SSH_USER }}
        ssh_host: ${{ env.SSH_HOST }}
        ssh_private_key: ${{ env.SSH_PRIVATE_KEY }}
        step_name: ${{ inputs.step_name }}
        step_run: |
          #### ${{ inputs.step_name }}
          export DOCKER_HOST="ssh://${SSH_TARGET}"

          # cleanup sensitive variable before run
          sed -i '/^SSH_PRIVATE_KEY=/d' $GITHUB_ENV

          ${{ inputs.step_run }}

    - name: Cleanup Deploy Variables
      if: always()
      shell: bash
      run: |
        #### Cleanup exported variables
        sed -i '/^SSH_USER=/d' $GITHUB_ENV
        sed -i '/^SSH_HOST=/d' $GITHUB_ENV
