name: Remote Deploy Commands
description: Helper to run remote ssh/docker commands
inputs:
  ssh_user:
    required: true
    description: ssh user
  ssh_host:
    required: true
    description: ssh host
  ssh_private_key:
    required: true
    description: ssh private key
  step_run:
    required: true
    description: commands script
  step_name:
    required: false
    description: step name
    default: Run Deploy Commands

runs:
  using: "composite"
  steps:
    - name: ${{ inputs.step_name }}
      uses: ./.github/composites/remote-ssh
      with:
        ssh_user: ${{ inputs.ssh_user }}
        ssh_host: ${{ inputs.ssh_host }}
        ssh_private_key: ${{ inputs.ssh_private_key }}
        step_name: ${{ inputs.step_name }}
        step_run: |
          #### ${{ inputs.step_name }}
          # cleanup sensitive variable before run
          sed -i '/^SSH_PKEY=/d' $GITHUB_ENV

          # export variable for implicit docker usage in run
          export DOCKER_HOST="ssh://${SSH_TARGET}"

          ${{ inputs.step_run }}
