# Modified Portainer install/update version:
# * disabled unused feature (edge)
# * use existing certs
#
# [Manual install](https://docs.portainer.io/start/install/server/swarm/linux)
# * curl -L https://downloads.portainer.io/ee-lts/portainer-agent-stack.yml -o portainer-agent-stack.yml
# * docker stack deploy -c portainer-agent-stack.yml portainer
#
# [Manual update](https://docs.portainer.io/start/upgrade/swarm)
# * docker pull portainer/portainer-ce:lts
# * docker service update --image portainer/portainer-ce:lts --publish-add 9443:9443 --force portainer_portainer
# * docker pull portainer/agent:lts
# * docker service update --image portainer/agent:lts --force portainer_agent 

version: '3.2'

services:
  agent:
    image: portainer/agent:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  # TODO: use Using your own SSL certificate on Docker Swarm via secrets
  #   https://docs.portainer.io/advanced/ssl#using-your-own-ssl-certificate-on-docker-swarm
  portainer:
    image: portainer/portainer-ce:lts
    #### existing certs https://docs.portainer.io/advanced/ssl#using-your-own-ssl-certificate-on-docker-standalone
    #command: -H tcp://tasks.agent:9001 --tlsskipverify
    command: >
      -H tcp://tasks.agent:9001
      --sslcert /certs/live/${SERVER_NAME:-localhost}/fullchain.pem
      --sslkey /certs/live/${SERVER_NAME:-localhost}/privkey.pem
    ports:
      - "9443:9443"
      #### edge disabled
      #- "9000:9000"
      #- "8000:8000"
    volumes:
      - portainer_data:/data
      #### existing certs
      - ${DATA_ROOT:-.}/certbot/conf:/certs:ro
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
