# https://docs.github.com/en/rest/deployments/statuses
name: GitHub Deployment Status
description: Update GitHub deployment status state and additional information
inputs:
  token:
    required: true
    description: "GitHub token"
  state:
    required: true
    description: "State to set on deployment"
  deployment_id:
    required: false # otherwise DEPLOYMENT_ID environment variable
    description: "Deployment ID for state"

runs:
  using: "composite"
  steps:
    - name: Deployment Status (${{ inputs.state }})
      shell: bash
      env:
        ACTION_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        #### update deployment status with github API 
        set -x # 

        # Determine DEPLOYMENT_ID
        if [[ -n "${{ inputs.deployment_id }}" ]]; then
          DEPLOYMENT_ID="${{ inputs.deployment_id }}"
        elif [[ -n "${{ env.DEPLOYMENT_ID }}" ]]; then
          DEPLOYMENT_ID="${{ env.DEPLOYMENT_ID }}"
        else
          echo "Error: Deployment ID is not specified in inputs or environment variables."
          exit 1
        fi

        # status with link to current action run
        curl -X POST -H "Authorization: token ${{ inputs.token }}" \
          -d '{"state": "${{ inputs.state }}", "log_url": "${{ env.ACTION_RUN_URL }}"}' \
          https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses
