services:
  app:
    image: tmp:app
    build:
      dockerfile: Dockerfile
      args: { base: nginx:latest }
    hostname: app
    stop_grace_period: 1s
    command: /bin/sh -c "sed -i 's/80;/181;/' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "181:181"
    networks:
      - general_shared

  # # https://github.com/coturn/coturn/blob/master/docker/coturn/README.md
  # coturn:
  #   image: tmp:coturn
  #   build:
  #     dockerfile: Dockerfile
  #     args: { base: coturn/coturn:latest }
  #   hostname: coturn
  #   stop_grace_period: 1s
  #   # docker run --rm -ti --network=host coturn/coturn --help
  #   # --allowed-peer-ip
  #   # --external-ip='$$(detect-external-ip)'
  #  
  #   # Docker Desktop compose:
  #   #   rt -stun stun:host.docker.internal:3478
  #   #   rt -stun turn:192.168.65.3
  #   #   rt -stun turn:10.211.55.4
  #   #   turnutils_uclient 10.211.55.4 -DgX -u user -w pass -n 1 -c -y
  #   #   turnutils_uclient 172.21.0.1 -DgX -u user -w pass -n 1 -c -e 172.21.0.2
  #   #   --relay-ip=10.211.55.4 # --relay-ip=0.0.0.0
  #   command: >
  #     -n
  #     --listening-port=3478
  #     --relay-threads=1
  #     --no-multicast-peers
  #     --fingerprint
  #     --no-tls
  #     --no-dtls
  #     --no-tcp-relay
  #     --no-stun
  #     --user user:pass
  #     --lt-cred-mech
  #     --log-file=stdout
  #     --verbose
  #   network_mode: host
  #   # networks:
  #   #   - host

# swarm
networks:
  general_shared:
    external: true
  host:
    name: host
    external: true
