name: App All

on:
  workflow_dispatch:

# https://docs.github.com/en/actions/sharing-automations/reusing-workflows
jobs:
  stand:
    permissions:
      contents: read
      packages: write
      deployments: write
    uses: ./.github/workflows/stand-stack.yml
