# Infra general services (proxies to access dynamic app deployments)
name: General Services

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/composites/remote-deploy
        with:
          ssh_user: ${{ secrets.REMOTE_USER }}
          ssh_host: ${{ secrets.REMOTE_HOST }}
          ssh_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          step_run: |
            #### docker stack deploy of generatl services
            exit 111
            # docker stack deploy --with-registry-auth -c compose.yaml -c compose.release.yaml tt
