# Infra general services (proxies to access dynamic app deployments)
name: General Services

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      STACK_NAME: general
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/composites/remote-deploy
        with:
          ssh_user: ${{ secrets.REMOTE_USER }}
          ssh_host: ${{ secrets.REMOTE_HOST }}
          ssh_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          step_run: |
            #### docker stack deploy general services
            set -x
            docker stack deploy \
              -c ./deploy/_general/compose.yaml \
              -c ./deploy/_general/compose.swarm.yaml \
              ${{ env.STACK_NAME }}
            docker service update --force ${{ env.STACK_NAME }}_coturn
