name: Portainer Stack
run-name: Portainer ${{ github.sha }}

on:
  workflow_dispatch:

env:
  DOCKER_STACK_NAME: portainer
  ACTION_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.run_attempt == 1 }}

    permissions:
      deployments: write

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/
            deploy/portainer/

      - uses: ./.github/composites/deploy-begin
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: infra-portainer

      - uses: ./.github/composites/remote-deploy
        with:
          ssh_user: ${{ secrets.REMOTE_USER }}
          ssh_host: ${{ secrets.REMOTE_HOST }}
          ssh_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          step_run: |
            #### docker stack deploy
            set -x

            clean_deployment_id ${{ env.DOCKER_STACK_NAME }}

            export DATA_ROOT="/home/${{ secrets.REMOTE_USER }}"
            export SERVER_NAME=${{ secrets.REMOTE_HOST }}
            docker stack deploy \
              --with-registry-auth \
              --resolve-image always \
              -c deploy/portainer/portainer-agent-stack.yml \
              ${{ env.DOCKER_STACK_NAME }}

            save_deployment_id ${{ env.DOCKER_STACK_NAME }}

      - uses: ./.github/composites/deploy-status
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: ${{ job.status }}

  stop:
    runs-on: ubuntu-latest
    if: ${{ github.run_attempt > 1 }}
    permissions: 
      deployments: write

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/

      - uses: ./.github/composites/remote-deploy
        with:
          ssh_user: ${{ secrets.REMOTE_USER }}
          ssh_host: ${{ secrets.REMOTE_HOST }}
          ssh_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          step_run: |
            #### stop deployment
            set -x # debug
            load_deployment_id ${{ env.DOCKER_STACK_NAME }}
            docker stack rm ${{ env.DOCKER_STACK_NAME }}

      - name: Deployment Status (inactive)
        uses: ./.github/composites/deploy-status
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: 'inactive'
