name: Stop Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to stop'
        required: true
        type: string

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      # TODO: docker stack deploy (after sharing some vars: ssh_user ssh_host ssh_private_key DOCKER_HOST)

      - name: Stop Seployment
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "state": "inactive",
              "description": "Deployment stopped manually"
            }' \
            https://api.github.com/repos/${{ github.repository }}/deployments/${{ github.event.inputs.environment }}/statuses
