name: Portainer Deploy

on:
  workflow_dispatch: # allows the workflow to be triggered manually

env:
  DOCKER_STACK_NAME: portainer

jobs:
  deploy:
    name: Update Deployment
    runs-on: ubuntu-latest
    if: ${{ github.run_attempt == 1 }}

    # required to create deployment
    #   https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
    permissions:
      deployments: write  # to create/update deployment

    steps:
      - uses: actions/checkout@v4

      # https://docs.github.com/en/rest/deployments/deployments
      - name: Register Deployment
        run: |
          DEPLOYMENT_REGISTER=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "ref": "'${{ github.sha }}'",
              "environment": "infra-portainer",
              "payload": "{ \"state\": \"deploy-state\" }",
              "description": "Deploy request"
            }' \
            https://api.github.com/repos/${{ github.repository }}/deployments)
          echo "deployment: $DEPLOYMENT_REGISTER"
          DEPLOYMENT_ID=$(echo $DEPLOYMENT_REGISTER | jq -r .id)

          # to be used in steps
          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV
          # to be used in stop action
          echo "$DEPLOYMENT_ID" > portainer_deployment_id.txt

      # DOESN'T work because cannot get artifact between workflows
      - name: Upload Deployment ID
        uses: actions/upload-artifact@v4
        with:
          name: portainer_deployment_id
          path: portainer_deployment_id.txt

      # DOESN'T work because need PAT (or App) token to work with variables
      # - name: Save DEPLOYMENT_ID in Env
      #   run: |
      #     gh variable set DEPLOYMENT_ID --env infra-portainer --body "$DEPLOYMENT_ID"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/composites/remote-deploy
        with:
          ssh_user: ${{ secrets.REMOTE_USER }}
          ssh_host: ${{ secrets.REMOTE_HOST }}
          ssh_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          step_run: |
            echo "==== docker stack deploy: ${DOCKER_STACK_NAME}"
            docker stack deploy \
              --with-registry-auth \
              --resolve-image always \
              -c deploy/portainer/portainer-agent-stack.yml \
              ${DOCKER_STACK_NAME}

      # https://docs.github.com/en/rest/deployments/statuses
      - name: Update Deployment Status
        env:
          ACTION_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          echo "==== update deployment status: $DEPLOYMENT_ID",
          set -x # debug
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "state": "success",
              "log_url": "${{ env.ACTION_URL }}",
              "description": "Deployed successfully"
            }' \
            https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses

  stop:
    name: Stop Deployment
    runs-on: ubuntu-latest
    if: ${{ github.run_attempt > 1 }}

    steps:
      - name: Download Deployment ID
        uses: actions/download-artifact@v4
        with:
          name: portainer_deployment_id

      - name: Stop Deployment
        run: |
          echo "TODO: Stopping Deployment"
          set -x
          ls -la portainer_deployment_id.txt
          cat portainer_deployment_id.txt
          DEPLOYMENT_ID=$(cat portainer_deployment_id.txt)
          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID"
