name: Portainer Deploy

on:
  workflow_dispatch: # allows the workflow to be triggered manually

env:
  DOCKER_STACK_NAME: portainer
  ACTION_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  deploy:
    name: Update Deployment
    runs-on: ubuntu-latest
    if: ${{ github.run_attempt == 1 }}

    # required for deployment
    #   https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
    permissions:
      deployments: write  # create/update deployment/status

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/
            deploy/portainer/

      # https://docs.github.com/en/rest/deployments/deployments
      - name: Register Deployment
        run: |
          #### create deployment
          DEPLOYMENT_REGISTER=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "ref": "'${{ github.sha }}'",
              "environment": "infra-portainer"
            }' \
            https://api.github.com/repos/${{ github.repository }}/deployments)
          echo "deployment: $DEPLOYMENT_REGISTER"
          DEPLOYMENT_ID=$(echo $DEPLOYMENT_REGISTER | jq -r .id)
          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV

      - name: Deployment Status (in_progress)
        uses: ./.github/composites/deploy-status
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: in_progress

      - uses: ./.github/composites/remote-deploy
        with:
          ssh_user: ${{ secrets.REMOTE_USER }}
          ssh_host: ${{ secrets.REMOTE_HOST }}
          ssh_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          step_run: |
            #### docker stack deploy
            set -x

            # cleanup previous deployment id (fixes incorrect stop by previous re-run)
            ssh $SSH_TARGET rm -f portainer_deployment_id.txt

            export DATA_ROOT="/home/${{ secrets.REMOTE_USER }}"
            export SERVER_NAME=${{ secrets.REMOTE_HOST }}
            docker stack deploy \
              --with-registry-auth \
              --resolve-image always \
              -c deploy/portainer/portainer-agent-stack.yml \
              ${{ env.DOCKER_STACK_NAME }}

            # store deployment id allowing to make status inactive on stop
            ssh $SSH_TARGET sh -c "'echo $DEPLOYMENT_ID > portainer_deployment_id.txt'"

      - name: Deployment Status (success)
        uses: ./.github/composites/deploy-status
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: success

      - name: Deployment Status (failure)
        uses: ./.github/composites/deploy-status
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: failure

  stop:
    name: Stop Deployment
    runs-on: ubuntu-latest
    if: ${{ github.run_attempt > 1 }}
    permissions: 
      deployments: write # update deployment status

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/

      - uses: ./.github/composites/remote-deploy
        with:
          ssh_user: ${{ secrets.REMOTE_USER }}
          ssh_host: ${{ secrets.REMOTE_HOST }}
          ssh_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          step_run: |
            #### stop deployment
            set -x # debug

            # obtain deployment id to make status inactive
            DEPLOYMENT_ID=$(ssh $SSH_TARGET "cat portainer_deployment_id.txt")
            echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV

            # undeploy existing stack
            docker stack rm ${{ env.DOCKER_STACK_NAME }}

      - name: Deployment Status (inactive)
        uses: ./.github/composites/deploy-status
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: inactive
