name: Stack Deploy

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/src/Server

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: rlespinasse/github-slug-action@v5

      ################################################################
      # Server Build
      - uses: docker/setup-buildx-action@v3 #https://github.com/marketplace/actions/docker-setup-buildx
      - uses: docker/login-action@v3 #https://github.com/marketplace/actions/docker-login 
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5 #https://github.com/marketplace/actions/docker-metadata-action
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
      - uses: docker/build-push-action@v6 #https://github.com/marketplace/actions/build-and-push-docker-images
        with:
          context: .
          file: src/Server/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      #TODO: sign the published docker image

      ################################################################
      # Server Deploy (custom docker stack deploy step much faster than docker-stack-deploy action)
      - uses: ./.github/composites/remote-deploy
        env:
          # environment variables that are used for compose
          STAND_NAME: ${{ env.GITHUB_REF_POINT_SLUG }}
          STACK_NAME: stand-${{ env.GITHUB_REF_POINT_SLUG }}
          SERVER_NAME: ${{ secrets.REMOTE_HOST }}
          SERVER_IMAGE: ${{ steps.meta.outputs.tags }}
        with:
          ssh_user: ${{ secrets.REMOTE_USER }}
          ssh_host: ${{ secrets.REMOTE_HOST }}
          ssh_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          step_name: Stand Stack Deploy STAND_NAME=${{ env.STAND_NAME }} STACK_NAME=${{ env.STACK_NAME }}
          step_run: |
            #### stand stack deploy
            set -x

            # docker stack config -c compose.yaml -c compose.release.yaml # diagnose rendered stack
            docker stack deploy \
              --with-registry-auth \
              -c compose.yaml \
              -c compose.release.yaml \
              ${{ env.STACK_NAME }}

            # deploy test pages
            COMMIT_SHA=$GITHUB_SHA_SHORT #${COMMIT_SHA:0:7}
            COMMIT_DATETIME=$(git log -1 --format=%cd "--date=format:%Y-%m-%d %H:%M:%S") #$(date -u +"%Y-%m-%d %H:%M:%S")
            sed -i "s/\$COMMIT_SHA/${COMMIT_SHA}/g" pages/index.html
            sed -i "s/\$COMMIT_DATETIME/${COMMIT_DATETIME}/g" pages/index.html
            scp -r pages/ $SSH_TARGET:.
